version: "3.9"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: node
    container_name: mbti-survey-api
    restart: always
    env_file: .env
    ports:
      - 3000:3000
